audio:
- changed-files:
  - any-glob-to-any-file: 'src/Kaijinix.Audio*/**'

cpu:
- changed-files:
  - any-glob-to-any-file: ['src/ARMeilleure/**', 'src/Kaijinix.Cpu/**', 'src/Kaijinix.Memory/**']

gpu:
- changed-files:
  - any-glob-to-any-file: ['src/Kaijinix.Graphics.*/**', 'src/Spv.Generator/**', 'src/Kaijinix.ShaderTools/**']

'graphics-backend:opengl':
- changed-files:
  - any-glob-to-any-file: 'src/Kaijinix.Graphics.OpenGL/**'

'graphics-backend:vulkan':
- changed-files:
  - any-glob-to-any-file: ['src/Kaijinix.Graphics.Vulkan/**', 'src/Spv.Generator/**']

gui:
- changed-files:
  - any-glob-to-any-file: ['src/Kaijinix/**', 'src/Kaijinix.UI.Common/**', 'src/Kaijinix.UI.LocaleGenerator/**', 'src/Kaijinix.Gtk3/**']

horizon:
- changed-files:
  - any-glob-to-any-file: ['src/Kaijinix.HLE/**', 'src/Kaijinix.Horizon/**']

kernel:
- changed-files:
  - any-glob-to-any-file: 'src/Kaijinix.HLE/HOS/Kernel/**'

infra:
- changed-files:
  - any-glob-to-any-file: ['.github/**', 'distribution/**', 'Directory.Packages.props']
